services:
  postgres:
    build:
      context: .
      dockerfile: p_bench_docker_file
    image: "dev_alphava_docker_file"
    container_name: ${PG_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: ${PGDATA}
    volumes:
      - p_bench:/data/p_bench
    ports:
      - "6998:5432"
    restart: unless-stopped
volumes:
  p_bench:
    external: true